### ISSUE TITLE
What is the meaning of "could not find branch for..."

### ISSUE THREAD

**Issue by aey76** [ivanhofer/git-assistant#11]
What is the meaning of the error message:
"could not find branch for 'xxx' in Submodule 'xxx'. You have to checkout the branch manually"

And what should i do to fix that ?

**Comment by ivanhofer** [comment]
Hi, sorry for my late response. I didn't get a notification.
You have a "detached HEAD" in one of your submodules. The extension tries to find the matching branch of the last commit in that submodule. The last commit of the submodule does not match witch the HEAD of any of your branches.
To get rid of the "detached HEAD" status you have to either manually checkout a branch or create a new branch in your submodule.

Does this answer help you?

**Comment by aey76** [comment]
yes, thank you.
