### ISSUE TITLE
"...checking repository" message never goes away

### ISSUE THREAD

**Issue by gmaughan** [ivanhofer/git-assistant#12]
The '...checking repository' message that appears in the status bar does not seem to ever be cleared for me. It always shows up and always animates.

![image](https://user-images.githubusercontent.com/936398/83824926-254d4d00-a71b-11ea-8d05-4194ea646276.png)

I'm using a code-workspace with three sub-projects.

Its a minor annoyance. Otherwise a very useful plugin.

VSCODE v1.45.1
Git (Submodule) Assistant v1.3.3

**Comment by ivanhofer** [comment]
I can't reproduce this issue.
Could you please attach the log?
You can find it when clicking on the "...checking repository" button in the status-bar

**Comment by gmaughan** [comment]
I can't reproduce it again either. 

The only differences in my environment are an upgrade of VSCODE that may have improved something and I've started to work more in branches rather than `master`. Prior to posting this issue I was working only on `master` and have recently switched to using branches and pull request as we are adding more developers.

Apologies for the distraction.

**Comment by ivanhofer** [comment]
no problem 😉
everytime the extension displays a message in the vs code notification panel, the extension waits for 60 seconds until it continues checking for other "problems" in the repository. The "... is checking" in the statusbar will be displayed until all messages are either resolved (when you click on a action) or 60 seconds passed.
Maybe this was the case when you reported th issue.
