### ISSUE TITLE
Alternative solutions to excessive notifications?

### ISSUE THREAD

**Issue by JPalmerDev** [ivanhofer/git-assistant#18]
In the README:

> If you get too many notifications or if you always click on "yes" to let 'Git (Submodule) Assistant' resolve the problem for you, there is an option for most features to save you some time: if a feature is set to "auto", it will not display a notification and handle the problem automatically for you.

Are there really no other ways to deal with notifications than clicking no every time. Commonly if I'm doing some operation on master, getting prodded that I probably shouldn't work there is just disruptive rather than helpful.

Could there be an option for disabling certain categories of notification? That seems like a standard practice that allows expert users to work without as many interruptions.

**Comment by ivanhofer** [comment]
Hi,
you can disable every feature you want. The setting you are looking for is "git-assistant.branchWarn". Just search for it in the VS Code settings.

**Comment by JPalmerDev** [comment]
Oh, this is wonderful.
Didn't find this in my own searching!

Thank you!
