### ISSUE TITLE
No popups since version 1.3.0

### ISSUE THREAD

**Issue by aey76** [ivanhofer/git-assistant#9]
There are no warnings popups since version 1.3.0, all the warnings i used to get with version 1.2.2 like working on master branch, advice to push... are gone.

**Comment by ivanhofer** [comment]
Hi, can you please check your version of the extension? Wen I released version 1.3 I broke some things. 
But in version 1.3.3 everything should be fixed.

**Comment by aey76** [comment]
After update to latest version 1.3.3 and vscode 1.44.0 the popups got back.
thank you.
